config/routes.rb
Rails.application.routes.draw do
  get 'global_settings', to: 'global_settings#edit', as: 'global_settings'
  get 'screens_on', to: 'global_settings#screens_on', as: 'screens_on'
  get 'screens_off', to: 'global_settings#screens_off', as: 'screens_off'
  post 'global_settings', to: 'global_settings#update'

  devise_for :users, controllers: {
    omniauth_callbacks: 'auth'
  }

  presentation_superclass_methods = [:index, :show, :destroy]

  resources :users do
    get 'password', on: :member
    put 'password_update', on: :member
    get 'import', to: 'users#new_import', on: :collection
    post 'import', to: 'users#import', on: :collection
  end

  resources :presentations, only: presentation_superclass_methods do
    get 'display', on: :member
    get 'next', on: :collection
    get 'push', on: :member
    get 'preview', on: :member
    post 'mark_broken', on: :member
  end
  get 'presentations/:id/display/*path', to: 'presentations#display', format: false, as: 'display_presentation_path'
  get 'presentations/:id/preview/*path', to: 'presentations#display', format: false, as: 'display_preview_path'
  get 'presentations/card/:card', to: 'presentations#card', as: 'card_presentation'

  resources :slideshows, except: presentation_superclass_methods do
    resources :slides, shallow: true
  end

  resources :foldershows, except: presentation_superclass_methods

  resources :themes do
    resources :slideshows, shallow: true
  end

  get '/settings', to: 'users#settings', as: 'settings'
  get '/presentations', to: 'presentations#index', as: 'logged_in_home'
  get '/about', to: 'static#about', as: 'logged_out_home'
  get '/404', to: 'static#not_found', as: 'not_found'

  root 'presentations#index'

end

app/models/presentation.rb
require 'carrierwave/orm/activerecord'
class Presentation < ActiveRecord::Base
  BROKEN_MESSAGE_KEYS = %W{
    no_index_found
    presentation_timeout
    slide_timeout
  }

  scope :working, -> { where(broken_message_keys: nil) }

  serialize :broken_message_keys, Array

  belongs_to :user
  validates :name, :user, presence: true
  validates :name, uniqueness: {scope: :user}
  validate :foldershow_xor_slideshow
  validate :check_broken_message_keys
  before_save :uniq_broken_message_keys
  before_save :clear_broken_message_keys_before_save
  after_touch :clear_broken_message_keys_after_touch

  def slideshow?
    kind_of? Slideshow || type == Slideshow.name
  end

  def foldershow?
    kind_of? Foldershow || type == Foldershow.name
  end

  def mark_broken!(message_key)
    self.broken_message_keys += [message_key]
    self.save!
  end

  def broken_messages?
    !broken_message_keys.blank?
  end

  def self.broken_message_to_i18n_key(key)
    "activerecord.errors.models.presentation.broken_message.#{key}"
  end

  private

  def foldershow_xor_slideshow
    unless slideshow? ^ foldershow?
      errors.add(:base, :foldershow_xor_slideshow)
    end
  end

  def check_broken_message_keys
    broken_message_keys.each do |key|
      errors.add(:broken_message_keys, "\"#{key}\" is not a valid broken message") unless BROKEN_MESSAGE_KEYS.include? key
    end
  end

  def uniq_broken_message_keys
    broken_message_keys.uniq!
  end

  def clear_broken_message_keys_before_save
    if changed? && !broken_message_keys_changed?
      self.broken_message_keys = nil
    end
    self.broken_message_keys = nil if broken_message_keys.empty?
    @ran_before_save = true
  end

  def clear_broken_message_keys_after_touch
    return if @ran_before_save
    update_column :broken_message_keys, nil
  end

end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  PANESD_METHODS = [:display, :next, :card, :mark_broken]
  skip_after_action :verify_authorized, only: PANESD_METHODS
  skip_before_action :authenticate_user!, only: PANESD_METHODS
  before_action :verify_localhost, only: PANESD_METHODS
  before_action :set_presentation, only: [:show, :push, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token, only: [
    :display, # This is needed to be able to download .js files from foldershows
    :mark_broken
  ]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = policy_scope(Presentation)
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
  end

  def mark_broken
    message = params[:message].to_s
    unless Presentation::BROKEN_MESSAGE_KEYS.include?(message)
      render(status: :bad_request, plain: "Invalid message")
      return
    end

    presentation = Presentation.find_by_id!(params[:id])
    presentation.mark_broken!(message)
    render(nothing: true, status: :no_content)
  end

  # TODO: this could be improved to better "randomize" the selection by 
  # taking recently-played information in to account.
  def next
    offset = rand(Presentation.working.count)
    presentation = Presentation.working.offset(offset).select([:id]).first
    if presentation.nil?
      redirect_to logged_out_home_path
      return
    end
    redirect_to display_presentation_url(presentation)
  end

  # push whatever presentation is associated with given card id
  def card
    user = User.find_by_card_number(params[:card])
    unless user
      logger.warn "No user registered with card number: #{params[:card]}"
      render nothing: true
      return
    end
    @presentation = user.primary_presentation || user.presentations.first
    render(nothing: true) unless @presentation
    push
  end

  def push
    begin
      panesfe_endpoint = URI.parse GrowingPanes.config['panesfe_endpoint']
      Panesd.new(display_presentation_url(@presentation, host: panesfe_endpoint.host, port: panesfe_endpoint.port)).push
    rescue Errno::ECONNREFUSED
      flash[:error] = t('controllers.presentations.panesd_offline')
    else
      flash[:notice] = t('controllers.presentations.presentation_pushed')
    end
    redirect_to action: :index
  end

  # GET /presentations/1/display
  def display(previewing=false)
    presentation = Presentation.find_by_id!(params[:id])
    authorize presentation if previewing
    case presentation
    when Slideshow
      respond_to do |format|
        format.html do
          content = presentation.theme.content
          if previewing
            content = content.sub('</body>',
              '<script src="/javascripts/growingpanes.js"></script></body>')
          end
          render html: content.html_safe
        end
        format.json { render json: presentation.slides.rank(:row_order) }
      end
    when Foldershow

      if params[:path].blank?
        the_index = presentation.find_index
        if the_index
          redirect_to path: the_index, trailing_slash: previewing
        else
          presentation.mark_broken!(:no_index_found)
          redirect_to next_presentations_url
        end
        return
      end

      Zip::File.open(presentation.folder_zip.path) do |zipfile|
        tmpfile = Tempfile.new(["presentation_#{presentation.id}_", File.extname(params[:path])])
        overwrite = true # Need this so Rubyzip will write overwrite the (empty) new tmpfile
        zip_entry = zipfile.find_entry(params[:path])
        if zip_entry
          zip_entry.extract(tmpfile.path) { overwrite }
          send_file tmpfile.path, disposition: 'inline'
        else
          render template: 'static/not_found', status: 404
        end
      end

    else
      raise "Don't know how to display #{presentation.inspect}"
    end
  end

  def preview
    display(true)
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_presentation
    @presentation = policy_scope(Presentation).find_by_id!(params[:id])
    authorize @presentation
  end

  def verify_localhost
    return true if request.host == 'localhost'
    user_not_authorized
    return false
  end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
  def edit_presentation_path(presentation)
    case presentation
    when Slideshow then edit_slideshow_path(presentation)
    when Foldershow then edit_foldershow_path(presentation)
    else
      raise "Don't know how to make an edit path for #{presentation.inspect}"
    end
  end

  def full_broken_messages presentation
    presentation.broken_message_keys.collect do |key|
      I18n.t Presentation.broken_message_to_i18n_key(key)
    end.join(' ').html_safe
  end
end

app/views/presentations/_form.html.erb
<%= form_for @presentation, :html => { :class => "form presentation", :role => 'form' } do |f| %>

  <%= f.submit t('helpers.links.save'), :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            presentations_path, :class => 'btn btn-default' %>

    <% if @presentation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @presentation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label' %>
    <%= f.text_field :name, :class => 'form-control' %>
    <%= error_span(@presentation[:name]) %>
  </div>

  <div class="form-group">
    <%= f.label :theme_id, :class => 'control-label' %>
    <%= f.collection_select :theme_id, Theme.select(:id, :name), :id, :name %>
    <%= error_span(@presentation[:theme_id]) %>
  </div>

<!--   <div class="form-group">
    <div class="checkbox">
      <%= label_tag do %>
        <%= f.check_box :published %>
        <%= Presentation.human_attribute_name(:published) %>
      <%end%>
      <%= error_span(@presentation[:published]) %>
    </div>
  </div>

 -->
<% end %>

<%= if @presentation.id then render(partial: 'images_form') end%>

app/views/presentations/_images_form.html.erb
<div id="fileupload">
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Add files...</span>
                <input type="file" name="files[]" multiple>
            </span>
            <!--button type="submit" class="btn btn-primary start">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start upload</span>
            </button-->
            <button type="reset" class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel upload</span>
            </button>
            <!--button type="button" class="btn btn-danger delete">
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" class="toggle"-->
            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
            <%=t 'controllers.presentations.quota_available', available: number_to_human_size(@presentation.user.disk_available_mb.megabytes), total: number_to_human_size(@presentation.user.disk_quota_mb.megabytes)%>
        </div>
        <!-- The global progress state -->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</div>


<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <!--input type="checkbox" name="delete" value="1" class="toggle"-->
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>

<script>
/*jslint unparam: true, regexp: true */
/*global window, $ */
$(function () {
    'use strict';

    $.widget('blueimp.fileupload', $.blueimp.fileupload, {
        processActions: {
            checkDiskAvailable: function (data) {
                var dfd = $.Deferred(),
                    file = data.files[data.index];
                if (file.size < this.options.diskAvailableB) {
                    this.options.diskAvailableB -= file.size
                    dfd.resolveWith(this, [data]);
                } else {
                    file.error = <%= I18n.t('errors.messages.would_exceed_quota_static').to_json.html_safe -%>;
                    data.files.error = true;
                    dfd.rejectWith(this, [data]);
                }
                return dfd.promise();
            }
        }
    });

    // Change this to the location of your server-side upload handler:
    var url = <%=presentation_slides_url(@presentation).to_json.html_safe %>,
        uploadButton = $('<button/>')
            .addClass('btn btn-primary')
            .prop('disabled', true)
            .text('Processing...')
            .on('click', function () {
                var $this = $(this),
                    data = $this.data();
                $this
                    .off('click')
                    .text('Abort')
                    .on('click', function () {
                        $this.remove();
                        data.abort();
                    });
                data.submit().always(function () {
                    $this.remove();
                });
            });
    $('#fileupload').fileupload({
        url: url,
        type: 'POST',
        dataType: 'json',
        autoUpload: true,
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png|mp4|264)$/i,
        // maxFileSize: 5000000, // 5 MB
        // Enable image resizing, except for Android and Opera,
        // which actually support image resizing, but fail to
        // send Blob objects via XHR requests:
        disableImageResize: /Android(?!.*Chrome)|Opera/
            .test(window.navigator.userAgent),
        previewMaxWidth: 150,
        previewMaxHeight: 150,
        previewCrop: true,
        sequentialUploads: true,
        diskAvailableB: <%= @presentation.user.disk_available_b -%>,
        processQueue: [
            {
                action: 'checkDiskAvailable',
                always: true
            }
        ]
    }).on('fileuploadadd', function (e, data) {
        data.context = $('<div/>').appendTo('#files');
        $.each(data.files, function (index, file) {
            var node = $('<p/>')
                    .append($('<span/>').text(file.name));
            if (!index) {
                node
                    .append('<br>')
                    .append(uploadButton.clone(true).data(data));
            }
            node.appendTo(data.context);
        });
    }).on('fileuploadprocessalways', function (e, data) {
        var index = data.index,
            file = data.files[index],
            node = $(data.context.children()[index]);
        if (file.preview) {
            node
                .prepend('<br>')
                .prepend(file.preview);
        }
        if (file.error) {
            node
                .append('<br>')
                .append($('<span class="text-danger"/>').text(file.error));
        }
        if (index + 1 === data.files.length) {
            data.context.find('button')
                .text('Upload')
                .prop('disabled', !!data.files.error);
        }
    }).on('fileuploadprogressall', function (e, data) {
        var progress = parseInt(data.loaded / data.total * 100, 10);
        $('#progress .progress-bar').css(
            'width',
            progress + '%'
        );
    }).on('fileuploaddone', function (e, data) {
        $.each(data.result.files, function (index, file) {
            if (file.url) {
                var link = $('<a>')
                    .attr('target', '_blank')
                    .prop('href', file.url);
                $(data.context.children()[index])
                    .wrap(link);
            } else if (file.error) {
                var error = $('<span class="text-danger"/>').text(file.error);
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            }
        });
    }).on('fileuploadfail', function (e, data) {
        $.each(data.files, function (index) {
            var error = $('<span class="text-danger"/>').text('File upload failed.');
            $(data.context.children()[index])
                .append('<br>')
                .append(error);
        });
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');

    // Load existing files:
    $('#fileupload').addClass('fileupload-processing');
    $.ajax({
        // Uncomment the following to send cross-domain cookies:
        //xhrFields: {withCredentials: true},
        url: url,
        dataType: 'json',
        context: $('#fileupload')[0]
    }).always(function () {
        $(this).removeClass('fileupload-processing');
    }).done(function (result) {
        $(this).fileupload('option', 'done')
            .call(this, $.Event('done'), {result: result});
    });

});
</script>

app/views/presentations/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%- model_class = Presentation -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
      <p class="lead"><%=t( 'controllers.presentations.explanation').html_safe %></p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="text-center">
      <%= link_to t('.new', :default => t("helpers.titles.new", model: Slideshow.model_name.human.titleize)),
                  new_slideshow_path,
                  :class => 'btn btn-primary' %>
    </div>
  </div>
  <div class="col-md-8">
    <p><%=t( 'controllers.presentations.slideshow_explanation').html_safe %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="text-center">
      <%= link_to t('.new', :default => t("helpers.titles.new", model: Foldershow.model_name.human.titleize)),
                  new_foldershow_path,
                  :class => 'btn btn-primary' %>
    </div>
  </div>
  <div class="col-md-8">
    <p><%=t( 'controllers.presentations.foldershow_explanation').html_safe %></p>
  </div>
</div>

<div class="row"><div class="col-md-12">
<%if @presentations.blank? %>
  <h4>
    <%=sprintf(t( 'controllers.presentations.no_presentations'), new_slideshow_path).html_safe %>
  </h4>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
<!--       <th><%= model_class.human_attribute_name(:published) %></th> -->
      <%if @presentations.any?{|p|p.user != current_user}%><th><%= model_class.human_attribute_name(:user_id) %></th><%end%>
      <th><%=t "helpers.notes" %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @presentations.each do |presentation| %>
      <tr class="<%= presentation.broken_messages? ? 'danger' : ''%>">
        <td>
          <% if presentation.kind_of?(Slideshow) && 
            presentation.slides.rank(:row_order).first &&
            presentation.slides.rank(:row_order).first.image &&
            presentation.slides.rank(:row_order).first.image.thumb %>
            <%= link_to image_tag(presentation.slides.rank(:row_order).first.image.thumb.url), presentation_path(presentation) %>
          <% end %>
          <p><%= link_to presentation.name, presentation_path(presentation) %></p>
        </td>
<!--         <td><%= presentation.published %></td> -->
      <%if @presentations.any?{|p|p.user != current_user}%><td><%= presentation.user.email %></td><%end%>
        <td class="<%= presentation.broken_messages? ? 'text-danger' : ''%>"><%if presentation.broken_messages?%><strong><%= t 'controllers.presentations.broken_headsup' %></strong> <%= full_broken_messages(presentation) %><%end%></td>
        <td><%=time_tag presentation.updated_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_presentation_path(presentation), :class => 'btn btn-default btn-xs' %>
          <% if policy(presentation).push? %>
            <%= link_to t('.push', :default => t("helpers.links.push")),
                        push_presentation_path(presentation), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      presentation_path(presentation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div></div>

app/views/presentations/new.html.erb
<%- model_class = Presentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/presentations/new_folder.html.erb
<%- model_class = Presentation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'folder_form' %>

app/views/presentations/show.html.erb
<%- model_class = @presentation.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @presentation.name %></dd>
<!--   <dt><strong><%= model_class.human_attribute_name(:published) %>:</strong></dt>
  <dd><%= @presentation.published %></dd> -->
  <% if @presentation.kind_of? Foldershow %>
    <dt><strong><%= model_class.human_attribute_name(:folder_zip) %>:</strong></dt>
    <dd><%= @presentation.folder_zip.to_s.split('/').last %></dd>
  <% elsif @presentation.kind_of? Slideshow %>
    <dt><strong><%= model_class.human_attribute_name(:slides) %>:</strong></dt>
    <dd><% @presentation.slides.rank(:row_order).each do |slide| %><%=image_tag slide.image.thumb.url%><% end %></dd>
  <% end %>

</dl>

<%= link_to t('.preview', :default => t("helpers.links.preview")),
              preview_presentation_path(@presentation), :class => 'btn btn-default', target: '_blank'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_presentation_path(@presentation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              presentation_path(@presentation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>