config/routes.rb
Rails.application.routes.draw do
  get 'global_settings', to: 'global_settings#edit', as: 'global_settings'
  get 'screens_on', to: 'global_settings#screens_on', as: 'screens_on'
  get 'screens_off', to: 'global_settings#screens_off', as: 'screens_off'
  post 'global_settings', to: 'global_settings#update'

  devise_for :users, controllers: {
    omniauth_callbacks: 'auth'
  }

  presentation_superclass_methods = [:index, :show, :destroy]

  resources :users do
    get 'password', on: :member
    put 'password_update', on: :member
    get 'import', to: 'users#new_import', on: :collection
    post 'import', to: 'users#import', on: :collection
  end

  resources :presentations, only: presentation_superclass_methods do
    get 'display', on: :member
    get 'next', on: :collection
    get 'push', on: :member
    get 'preview', on: :member
    post 'mark_broken', on: :member
  end
  get 'presentations/:id/display/*path', to: 'presentations#display', format: false, as: 'display_presentation_path'
  get 'presentations/:id/preview/*path', to: 'presentations#display', format: false, as: 'display_preview_path'
  get 'presentations/card/:card', to: 'presentations#card', as: 'card_presentation'

  resources :slideshows, except: presentation_superclass_methods do
    resources :slides, shallow: true
  end

  resources :foldershows, except: presentation_superclass_methods

  resources :themes do
    resources :slideshows, shallow: true
  end

  get '/settings', to: 'users#settings', as: 'settings'
  get '/presentations', to: 'presentations#index', as: 'logged_in_home'
  get '/about', to: 'static#about', as: 'logged_out_home'
  get '/404', to: 'static#not_found', as: 'not_found'

  root 'presentations#index'

end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :user
  has_many :presentations
  validates :user, presence: true
  before_validation :defaults

  def defaults
    self.content ||= ''
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = policy_scope(Theme)
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
    authorize @theme
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)
    authorize @theme
    @theme.user = current_user

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = policy_scope(Theme).find_by_id!(params[:id])
      authorize @theme
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:name, :content, :description)
    end
end

app/views/themes/_form.html.erb
<%= form_for @theme, html: { class: "theme" } do |f| %>

    <% if @theme.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @theme.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
    <%= f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, :class => 'form-control' %>
    <%= f.error_span(:description) %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => 'form-control', rows: 15 %>
    <%= f.error_span(:content) %>
  </div>


  <div class="form-group">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              themes_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<%- model_class = Theme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/themes/index.html.erb
<%- model_class = Theme -%>
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
      <p class="lead"><%=t( 'controllers.themes.explanation').html_safe %></p>
    </div>
  </div>
</div>

<div class="row"><div class="col-md-12">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:user_id) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @themes.each do |theme| %>
        <tr>
          <td><%= link_to theme.name, theme_path(theme) %></td>
          <td><%= theme.user.email %> </td>
          <td><%= theme.description %></td>
          <td><%=l theme.created_at %></td>
          <td>
            <%= link_to t('controllers.themes.use_this_theme'), new_theme_slideshow_path(theme), :class => 'btn btn-default btn-xs' %>
            <% if policy(theme).edit? %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_theme_path(theme), :class => 'btn btn-default btn-xs' %>
            <% end %>
            <% if policy(theme).destroy? %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          theme_path(theme),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div></div>
<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_theme_path,
            :class => 'btn btn-primary' %>

app/views/themes/new.html.erb
<%- model_class = Theme -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/themes/show.html.erb
<%- model_class = Theme -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @theme.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @theme.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><pre class="pre-scrollable"><%= @theme.content %></pre></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              themes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_theme_path(@theme), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              theme_path(@theme),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>