config/routes.rb
Rails.application.routes.draw do
  get 'global_settings', to: 'global_settings#edit', as: 'global_settings'
  get 'screens_on', to: 'global_settings#screens_on', as: 'screens_on'
  get 'screens_off', to: 'global_settings#screens_off', as: 'screens_off'
  post 'global_settings', to: 'global_settings#update'

  devise_for :users, controllers: {
    omniauth_callbacks: 'auth'
  }

  presentation_superclass_methods = [:index, :show, :destroy]

  resources :users do
    get 'password', on: :member
    put 'password_update', on: :member
    get 'import', to: 'users#new_import', on: :collection
    post 'import', to: 'users#import', on: :collection
  end

  resources :presentations, only: presentation_superclass_methods do
    get 'display', on: :member
    get 'next', on: :collection
    get 'push', on: :member
    get 'preview', on: :member
    post 'mark_broken', on: :member
  end
  get 'presentations/:id/display/*path', to: 'presentations#display', format: false, as: 'display_presentation_path'
  get 'presentations/:id/preview/*path', to: 'presentations#display', format: false, as: 'display_preview_path'
  get 'presentations/card/:card', to: 'presentations#card', as: 'card_presentation'

  resources :slideshows, except: presentation_superclass_methods do
    resources :slides, shallow: true
  end

  resources :foldershows, except: presentation_superclass_methods

  resources :themes do
    resources :slideshows, shallow: true
  end

  get '/settings', to: 'users#settings', as: 'settings'
  get '/presentations', to: 'presentations#index', as: 'logged_in_home'
  get '/about', to: 'static#about', as: 'logged_out_home'
  get '/404', to: 'static#not_found', as: 'not_found'

  root 'presentations#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
    :rememberable, 
    :trackable, 
    :validatable,
    :omniauthable,
    omniauth_providers: [:google_oauth2]
  validates :email, presence: true, uniqueness: true
  validates :uid, presence: true, uniqueness: true
  validates :provider, presence: true
  validates :role, presence: true
  validate :primary_presentation_belongs_to_user

  has_many :presentations

  belongs_to :primary_presentation, class_name: 'Presentation'

  enum role: {
    user: 0, 
    admin: 100, 
    superuser: 200
  }

  def adminish?
    admin? || superuser?
  end

  def primary_presentation_belongs_to_user
    if primary_presentation && primary_presentation.user.id != self.id 
      errors.add(:primary_presentation_id, :must_belong_to_user)
    end
  end

  def self.find_or_create_with_omniauth(auth)
    find_by(uid: auth["uid"], provider: auth["provider"]) ||
    create!(
      provider:   auth["provider"],
      uid:        auth["uid"],
      given_name: auth["info"]["given_name"] || auth["info"]["first_name"],
      family_name:auth["info"]["family_name"] || auth["info"]["last_name"],
      email:      auth["info"]["email"],
      role:       User.roles["user"]
    )
  end

  def disk_used_b
    return 0 unless upload_eligible?
    return 0 unless Dir.exist?(absolute_upload_path)
    # gets usage in kb then calculates mb. User gets 4k credit for dir size
    (`du -sb "#{absolute_upload_path}"`.split("\t").first.to_i - 4.kilobytes).to_f
  end

  def disk_used_mb
    disk_used_b / 1.megabyte
  end

  def disk_available_mb
    return 0 unless upload_eligible?
    disk_quota_mb - disk_used_mb
  end

  def disk_available_b
    disk_available_mb.megabytes
  end

  def disk_quota_mb
    custom_disk_quota_mb || GrowingPanes.config['default_disk_quota_mb']
  end

  def self.upload_base
    if GrowingPanes.config['upload_url_prefix'].blank?
      return Rails.env
    end
    File.join(GrowingPanes.config['upload_url_prefix'], Rails.env)
  end

  def upload_dir
    raise "Unsaved users can't have an upload_dir" unless upload_eligible?
    File.join(self.class.upload_base, "user_#{id}")
  end

  def absolute_upload_path
    File.join BaseUploader.root.call, upload_dir
  end

  def ensure_upload_dir
    FileUtils.mkdir_p(absolute_upload_path)
  end

  def upload_eligible?
    !id.nil?
  end

  protected

  # we don't want to force passwords on the normal case of 
  # signing in with google
  def password_required?
    return false if provider.to_s == 'google_oauth2'
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:settings, :index, :new, :create]

  def index
    raise Pundit::NotAuthorizedError unless policy(:user).create?
    @users = policy_scope(User).paginate(page: params[:page])
  end

  def new
    @user = User.new
    authorize @user
  end

  def destroy
    if @user.destroy
      flash.notice = "User #{@user.email.inspect} was destroyed"
    else
      flash.error = "An error occurred #{@user.errors.full_messages.inspect}"
    end
    redirect_to :users
  end


  def create
    @user = User.new
    authorize @user
    @user.provider = "devise"
    @user.attributes = user_params
    @user.uid = SecureRandom.urlsafe_base64

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def settings
    @user = current_user
    authorize @user
    render :edit
  end

  def update
    respond_to do |format|
      @user.attributes = user_params
      if params[:user][:use_default_disk_quota] == "true"
        @user.custom_disk_quota_mb = nil
      end
      if @user.save
        format.html { redirect_to @user == current_user ? logged_in_home_path : users_path, notice: 'User settings updated successfully.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def password_update
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    respond_to do |format|
      if @user.save
        format.html { redirect_to logged_in_home_path, notice: I18n.t('controllers.users.password_changed') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :password }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    permitted_attributes(@user)
  end

  def set_user
    if params[:id].nil?
      logger.debug "Tried to set user but didn't have a user id!"
    end
    @user = policy_scope(User).find_by_id!(params[:id])
    authorize @user
  end
end

app/views/users/_form.html.erb
<%= form_for @user, html: { class: "user form-horizontal" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <% if @user.new_record? %>
        <%= f.email_field :email, class: 'form-control' %>
      <% else %>
        <p class="form-control-static"><%= @user.email %></p>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :given_name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :given_name, class: 'form-control' %>
    </div>
    <%= f.error_span(:given_name) %>
  </div>

  <div class="form-group">
    <%= f.label :family_name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :family_name, class: 'form-control' %>
    </div>
    <%= f.error_span(:family_name) %>
  </div>

  <% if policy(@user).permitted_attributes.include?(:role) %>
    <div class="form-group">
      <%= label_tag User.human_attribute_name(:provider), nil, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <% [%w{google_oauth2 Google},%w{devise Username/Password}].each do |value, display_name| %>
          <div class="radio">
            <%= content_tag :label do
              [f.radio_button(:provider, value), display_name].join.html_safe
            end
            %>
          </div>
        <% end %>
      </div>
      <%= f.error_span(:provider) %>
    </div>
  <% end %>

  <% if policy(@user).permitted_attributes.include?(:password) %>
    <% if @user.new_record? %>
      <div class="form-group">
        <%= f.label :password, class: 'control-label col-sm-2' %>
        <div class="col-sm-10">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <%= f.error_span(:password) %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, class: 'control-label col-sm-2' %>
        <div class="col-sm-10">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.error_span(:password_confirmation) %>
      </div>
    <% else %>
      <div class="form-group">
        <%= f.label :password, class: 'control-label col-sm-2' %>
        <div class="col-sm-10">
          <%= link_to t('controllers.users.change_password'), password_user_path(@user), class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :card_number, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <% if policy(@user).permitted_attributes.include?(:card_number) %>
        <%= f.number_field :card_number, class: 'form-control' %>
      <% else %>
        <p class="form-control-static"><%= @user.card_number %></p>
      <% end %>
    </div>
    <%= f.error_span(:card_number) %>
  </div>

  <% if policy(@user).permitted_attributes.include?(:role) %>
    <div class="form-group">
      <%= label_tag User.human_attribute_name(:role), nil, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <% %w{user admin}.each do |role| %>
          <div class="radio">
            <%= content_tag :label do
              [f.radio_button(:role, role), User.human_attribute_name("role/#{role}")].join.html_safe
            end
            %>
          </div>
        <% end %>
      </div>
      <%= f.error_span(:role) %>
    </div>
  <% end %>

  <% if policy(@user).permitted_attributes.include?(:custom_disk_quota_mb) %>
    <div class="form-group">
      <%= f.label :custom_disk_quota_mb, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">

        <div class="radio">
          <label>
            <input 
              id="user_use_default_disk_quota" 
              value="true"
              name="user[use_default_disk_quota]" type="radio"
              <% if @user.custom_disk_quota_mb.nil? -%>
                checked="checked"
              <% end -%>
            />
            <%=t 'controllers.users.use_default', default_quota: GrowingPanes.config['default_disk_quota_mb'] %>
          </label>
        </div>

        <div class="radio form-inline">
          <label>
            <input 
              id="user_use_custom_disk_quota" 
              value="false"
              name="user[use_default_disk_quota]" type="radio"
              <% if !@user.custom_disk_quota_mb.nil? -%>
                checked="checked"
              <% end -%>
            />
            <%=t 'controllers.users.use_custom' %>
          </label>
          <div class="input-group">
            <%= f.number_field :custom_disk_quota_mb, min: 0, step: 1, class: 'form-control', disabled: !@user.custom_disk_quota_mb %>
            <span class="input-group-addon">MB</span>
          </div>
        </div>

      </div>
      <%= f.error_span(:custom_disk_quota_mb) %>
    </div>
  <% end %>

  <% unless @user.new_record? %>
    <div class="form-group">
      <%= f.label :primary_presentation_id, class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= f.collection_select :primary_presentation_id, @user.presentations, :id, :name, {}, class: 'form-control' %>
      </div>
      <%= f.error_span(:primary_presentation) %>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('helpers.links.save'), class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
            users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script>
  $(function(){
    $('input[type="radio"]').change(function(){
      var checkbox = $('#user_use_default_disk_quota')
      $('#user_custom_disk_quota_mb').prop('disabled', checkbox.is(':checked'))
    })
  })
</script>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t 'controllers.users.edit.title', :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <% if policy(:user).new? %>
      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>
    <% end %>
    <% if policy(:user).import? %>
      <%= link_to t('.import', :default => t("helpers.links.import")),
            import_users_path,
            :class => 'btn btn-primary' %>
    <% end %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:given_name) %></th>
      <th><%= model_class.human_attribute_name(:family_name) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:custom_disk_quota_mb) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= user.given_name %></td>
        <td><%= user.family_name %></td>
        <td><%= user.provider %></td>
        <td><%= user.role %></td>
        <td><%= user.last_sign_in_at ? user.last_sign_in_at.to_date.to_s(:rfc822) : "never" %></td>
        <td><%= user.custom_disk_quota_mb || "default"  %></td>
        <td>
          <% if policy(user).edit? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if policy(user).destroy? %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/new_import.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.import', 'Import %{model}'], :model => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag import_users_path, html: { class: "user form-horizontal" } do |f| %>

  <% @users.each do |user| %>
    <% if user.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= label_tag :import_file, t('controllers.users.users_file'), :class => 'control-label' %>
    <%= file_field :import_file, :class => 'form-control' %>
    <div class="help-block">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= submit_tag t('helpers.links.save'), class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
            users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/password.html.erb
<%= form_for @user, url: password_update_user_path(@user), method: :put, html: { class: "user form-horizontal" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if policy(@user).permitted_attributes.include?(:password) %>
    <div class="form-group">
      <%= f.label :password, User.human_attribute_name(:password), class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <%= f.error_span(:password) %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, User.human_attribute_name(:password_confirmation), class: 'control-label col-sm-2' %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.error_span(:password_confirmation) %>
    </div>

  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('helpers.links.save'), class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
            users_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:given_name) %>:</strong></dt>
  <dd><%= @user.given_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:family_name) %>:</strong></dt>
  <dd><%= @user.family_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= @user.uid %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @user.provider %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @user.role %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:custom_disk_quota_mb) %>:</strong></dt>
  <dd><%= @user.custom_disk_quota_mb %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>