config/routes.rb
Rails.application.routes.draw do
  get 'global_settings', to: 'global_settings#edit', as: 'global_settings'
  get 'screens_on', to: 'global_settings#screens_on', as: 'screens_on'
  get 'screens_off', to: 'global_settings#screens_off', as: 'screens_off'
  post 'global_settings', to: 'global_settings#update'

  devise_for :users, controllers: {
    omniauth_callbacks: 'auth'
  }

  presentation_superclass_methods = [:index, :show, :destroy]

  resources :users do
    get 'password', on: :member
    put 'password_update', on: :member
    get 'import', to: 'users#new_import', on: :collection
    post 'import', to: 'users#import', on: :collection
  end

  resources :presentations, only: presentation_superclass_methods do
    get 'display', on: :member
    get 'next', on: :collection
    get 'push', on: :member
    get 'preview', on: :member
    post 'mark_broken', on: :member
  end
  get 'presentations/:id/display/*path', to: 'presentations#display', format: false, as: 'display_presentation_path'
  get 'presentations/:id/preview/*path', to: 'presentations#display', format: false, as: 'display_preview_path'
  get 'presentations/card/:card', to: 'presentations#card', as: 'card_presentation'

  resources :slideshows, except: presentation_superclass_methods do
    resources :slides, shallow: true
  end

  resources :foldershows, except: presentation_superclass_methods

  resources :themes do
    resources :slideshows, shallow: true
  end

  get '/settings', to: 'users#settings', as: 'settings'
  get '/presentations', to: 'presentations#index', as: 'logged_in_home'
  get '/about', to: 'static#about', as: 'logged_out_home'
  get '/404', to: 'static#not_found', as: 'not_found'

  root 'presentations#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : t('product_name') %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>

      <%= javascript_include_tag "application" %>
    </head>
    <body>

      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%=current_user ? logged_in_home_path : logged_out_home_path%>"><%=t 'product_name'%></a>
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <% if current_user %>
                <li><%= link_to Theme.model_name.human.pluralize, themes_path  %></li>
                <% if policy(:global_settings).edit? %>
                  <li><%= link_to t('controllers.settings.edit.title'), global_settings_path  %></li>
                <% end %>
                <% if policy(:user).create? %>
                  <li><%= link_to User.model_name.human.pluralize, users_path %></li>
                <% end %>
              <% end %>
              <li><%= link_to t('helpers.links.help'), "https://github.com/growingpanes/growingpanes/wiki"  %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li>
                  <a href="<%=url_for new_user_session_path%>">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                    <%=t 'nav.login' %>
                  </a>
                </li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <i class="fa fa-user fa-lg"></i> <%= current_user.email %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%=link_to t('nav.settings'), settings_path %></li>
                    <% if policy(:global_settings).edit? %>
                      <li><%= link_to t('controllers.settings.screens_on'), screens_on_path  %></li>
                      <li><%= link_to t('controllers.settings.screens_off'), screens_off_path  %></li>
                    <% end %>
                    <li class="divider"></li>
                    <li><%=link_to t('nav.logout'), destroy_user_session_path, method: :delete%></li>
                  </ul>
                </li>
              <% end -%>
            </ul>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <%= interactive_mode_warning %>
            
            <%= bootstrap_flash(class: 'alert-dismissible').gsub('<button class="close" ', '<button type="button" class="close" ').html_safe %>
            
            <%= yield %>
          </div>
        </div><!--/row-->

      </div> <!-- /container -->
      <% if %w{development test}.include?(Rails.env) %>
        <script>
        $(function(){
          var s=document.createElement("script");
          s.onload = function(){
            bootlint.showLintReportForCurrentDocument(["W013"], {
              problemFree: false
            });
          };
          s.src="https://maxcdn.bootstrapcdn.com/bootlint/latest/bootlint.min.js";
          document.body.appendChild(s)
        })
        </script>
      <% end %>

    </body>
    </html>